### ISSUE TITLE
not portable to MSVC

### ISSUE THREAD

**Issue by TrianglesPCT** [lemire/fastmod#1]
__uint128_t is not available on msvc.

Perhaps replace the __uint128_t stuff with custom implementation?

Looks like all it needs to implement is mul(128,32)

Can skip the right shift, just grab upper 64 bits

**Comment by lemire** [comment]
Solved by PR https://github.com/lemire/fastmod/pull/2

**Comment by lemire** [comment]
Ack. to @Niadb

**Comment by lemire** [comment]
Closing.
