### ISSUE TITLE
Allow signed 32 bit division on MSVC

### ISSUE THREAD

**Issue by JAicewizard** [lemire/fastmod#13]
If I am not wrong, `__mulh` is available on MSVC, would it be possible to use this for MSVC to allow 32 bit signed division?

I am not in the possession of MSVC so I cannot test this, but the change would be trivial

**Comment by lemire** [comment]
Pull request invited.

**Comment by JAicewizard** [comment]
(Or if you are able to test, I can try a simple PR)

**Comment by JAicewizard** [comment]
I noticed that the tests for [cef71e5663ed09bbec3df1461c5216422f3d29ee](https://github.com/lemire/fastmod/commit/e79b3a422cb4f80dc5aa95cddbd6613ae81be837) already worked in CI, any reason the `fastdiv_s32` was later hidden from MSVC?

I didn't intend to imply you should implement it, but if this PR stays open others can know it is a wanted feature and work on it.

I personally don't have access to a windows machine, not do I know someone that does that I can use for this purpose

**Comment by lemire** [comment]
I had to check my notes and run some verifications, but `__mulh` does not actually compute the most significant 64 bits of a signed multiplication as required by the code.

> if this PR stays open others can know it is a wanted feature and work on it

I personally do not want this feature, but if someone needs it and they contribute it to the code, it will be well received.

If you could document why this is needed, maybe I could be convinced to entice people to work on this issue. As things stand, it is not very interesting.

**Comment by JAicewizard** [comment]
> I had to check my notes and run some verifications, but __mulh does not actually compute the most significant 64 bits of a signed multiplication as required by the code.

Ah, that is very odd, as it is contrary to the documentation

> If you could document why this is needed, maybe I could be convinced to entice people to work on this issue. As things stand, it is not very interesting.

I completely understand that the goal of this repository is not aligned with what I want from it. You can keep it closed if you want to.

**Comment by lemire** [comment]
> Ah, that is very odd, as it is contrary to the documentation

Can you elaborate?

We need to implement the following function:

```
uint64_t mul128_s32(uint64_t lowbits, int32_t d) {
  return (((__int128_t)lowbits * d)) >> 64;
}
```

Which compiles to something like this (clang)...

```asm
mul128_s32(unsigned long, int):                       # @mul128_s32(unsigned long, int)
        movsxd  rax, esi
        mov     rcx, rax
        sar     rcx, 63
        mul     rdi
        imul    rcx, rdi
        add     rcx, rdx
        mov     rax, rcx
        ret
```

Or (GCC)

```asm
mul128_s32(unsigned long, int):
        movsx   rsi, esi
        mov     rax, rsi
        cqo
        mov     rax, rdi
        mov     rcx, rdx
        mul     rsi
        imul    rcx, rdi
        add     rcx, rdx
        mov     rax, rcx
        ret
```

Can you elaborate as to why you think that this is what `__mulh` is equivalent to?

**Comment by JAicewizard** [comment]
I have got msvc to work under wine, and I think I understand the issue. The current implementation also uses intrinsics only supported on x86 which. Will leave this unaddressed until MSVC fixes 128 bit integer support.

For my usecase I will just adapt the fastmod method to use the 128 bit type already included in the project I am using it for, with attribution. I think that is allowed by the license

**Comment by lemire** [comment]
> The current implementation also uses intrinsics only supported on x86 which

I don't think that's true. If so, I'd like you to elaborate. Under Visual Studio, I believe we assume a 64-bit build, but that could be ARM64 or x64.

>  I think that is allowed by the license

You can reuse this code as you see fit, modifying it as needed. It is only a header that I provide for convenience.

I recommend you cite:

Lemire et al., [Faster Remainder by Direct Computation: Applications to Compilers and Software Libraries](https://arxiv.org/abs/1902.01961), Software: Practice and Experience 49 (6), 2019. https://arxiv.org/abs/1902.01961

In this manner, anyone who wants to understand can refer to the paper as documentation.

**Comment by JAicewizard** [comment]
> I don't think that's true. If so, I'd like you to elaborate. Under Visual Studio, I believe we assume a 64-bit build, but that could be ARM64 or x64.

I am once again mistake, only `__umulh` is x86 specific, `__mulh` does both x64 and ARM64

**Comment by lemire** [comment]
I think `__umulh` is always present in 64-bit targets under Visual Studio. We do not use `__mulh` but it appears to be x64-specific.
