### ISSUE TITLE
`fastdiv_s64()` and `fastmod_s64()` appear to be missing?

### ISSUE THREAD

**Issue by octurion** [lemire/fastmod#14]
I can see there is an implementation for `computeM_s64()` [here](https://github.com/lemire/fastmod/blob/a483e21bb80a5bd7e2521494a94786d0b27b58f7/include/fastmod.h#L165), but it appears this function is not being used anywhere in the repo.

What's more, I cannot seem to be able to find any references to either `fastdiv_s64()` or `fastmod_s64()`.

**Comment by lemire** [comment]
The function computeM_s64() was added with PR https://github.com/lemire/fastmod/pull/5 but never used.

I am going to remove it right now.

> fastdiv_s64() and fastmod_s64() appear to be missing?

A pull request is invited.
