### ISSUE TITLE
Error for MSVC (__umulh is not a constexpr function)

### ISSUE THREAD

**Issue by bernd5** [lemire/fastmod#8]
See here: https://godbolt.org/z/bjYn1s

It does not compile because __umulh is not a constexpr function...

**Comment by lemire** [comment]
Turns out to be a known issue: https://developercommunity.visualstudio.com/idea/434712/make-intrinsic-functions-supported-in-a-constexpr.html

This is surprising.

**Comment by lemire** [comment]
Fixed in the main branch. Thanks for the report.
