### ISSUE TITLE
Division by 1 returns 0

### ISSUE THREAD

**Issue by Kristine1975** [lemire/fastmod#9]
When `d` is 1, the computation in `computeM_u32` overflows to 0:

https://github.com/lemire/fastmod/blob/82f9506729dff97d36293aafe061babeefa9c41f/include/fastmod.h#L77

Then `M` is 0, and `fastdiv_u32(a,M)` returns 0 for any `a` (`fastmod_u32(a,M)` works correctly, as `a % 1 == 0`).

**Comment by lemire** [comment]
The `fastdiv_u32` function computers (a/d) given d>1, as documented.

```C++
// fastmod computes (a / d) given precomputed M for d>1
FASTMOD_API uint32_t fastdiv_u32(uint32_t a, uint64_t M) {
  return (uint32_t)(mul128_u32(M, a));
}
```
